### ISSUE TITLE
Won't start in SFOS 2.1.0

### ISSUE THREAD

**Issue by Ingvix** [hoelzro/harbour-sudoku#26]
It gives following error:
```
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Specified Desktop file does not exist "/usr/share/applications/harbour-sudoku.desktop"
[W] unknown:23 - file:///opt/sdk/harbour-sudoku/usr/share/harbour-sudoku/qml/harbour-sudoku.qml:23:30: Type PlayGamePage unavailable 
         initialPage: Component { PlayGamePage { } }
 
                                  ^
[W] unknown:32 - file:///opt/sdk/harbour-sudoku/usr/share/harbour-sudoku/qml/pages/PlayGamePage.qml:32:9: Type SudokuBoard unavailable 
             SudokuBoard {
 
             ^
[W] unknown:22 - file:///opt/sdk/harbour-sudoku/usr/share/harbour-sudoku/qml/pages/SudokuBoard.qml:22:1: Script file:///opt/sdk/harbour-sudoku/usr/share/harbour-sudoku/qml/pages/Sudoku.js unavailable 
     import "Sudoku.js" as S
 
     ^
[W] unknown:21 - file:///opt/sdk/harbour-sudoku/usr/share/harbour-sudoku/qml/pages/Sudoku.js:21:5: Expected token `}' 
         const GRID_SIZE       = 9;
 
         ^
```
I have no idea why it is expecting that token. They updated Qt to 5.6 so problem probably lies there. Any idea how to fix this?

**Comment by hoelzro** [comment]
I'm not sure; it's interesting that the last error happens with `const`.  I can look at it a bit this weekend.

**Comment by hoelzro** [comment]
I just tried building and running this on 2.1 - I can't even get the app to try to start. =( I get a message about the xcb backend not being available or something.

**Comment by Ingvix** [comment]
So you don't have any clue how to get past it?

**Comment by hoelzro** [comment]
Unfortunately not =(

**Comment by hoelzro** [comment]
@Ingvix Did you fix this in #27?  I built the app successfully, but my Jolla device won't accept it (it's still on 2.0.5.6), and I'd like to keep my device on the stable branch so I can push updates out.  Are all of the changes you've made compatibile with 2.0?  If so, I can push out a new version this weekend.

**Comment by Ingvix** [comment]
I can't really say for sure as I can't install the corresponding SDK version to 2.0.5 without removing the latest version and that would be quite a hassle to go back and forth just so try if it works.  All the changes before #27 were done on 2.0.5 so they should work and I don't think changing the constants to variables should break anything there so I'm pretty sure it works if you just build it for the right version.

**Comment by Ingvix** [comment]
Hassled a bit there. But yes, #27 fixed this issue and I'm pretty sure it works on 2.0 too if you just build it for it.

**Comment by Ingvix** [comment]
If your building it with the latest SDK version it probably won't work because the different version of Qt Quick.

**Comment by hoelzro** [comment]
@Ingvix Are the changes you've made significant enough to warrant a new release? I can install an older version of the SDK if that's the case!

**Comment by Ingvix** [comment]
Well I think they are. I'm sure many would like to be able to play it landscape mode and in the comments in the store someone was hoping for a way to reset the game. Also in the comments, those who have updated their phones 2.1 have been complaining how to doesn't start so I'm guessing it would also fix that issue for them.

I'm also not aware how does releasing a new version there actually works. Do you provide them with an rpm file or do you provide the sources and they build it for every OS version?

**Comment by hoelzro** [comment]
@Ingvix I upload the RPM and they review it - I don't know if there's a way to support both 2.0 and 2.1, though.  That would be ideal!

**Comment by Ingvix** [comment]
I'm pretty sure the built for 2.0.5 would also work with 2.1 as if I try to open the current version in the store the only error I get is this issue which is now fixed.

**Comment by hoelzro** [comment]
Ok, I'm going to try to build it for 2.0.5 - I'm having trouble at the moment, as the SDK I have (1611) claims to target 2.0.5, but I get QtCore 5.6 errors when I try to install the package!

**Comment by hoelzro** [comment]
I must have had some build files leftover from the early access 2.1 SDK - `git clean -fdx` and rebuilding fixed my issue

**Comment by hoelzro** [comment]
Ok, 0.4 has been submitted for QA.  Thanks for all your hard work and patience @Ingvix!

**Comment by hoelzro** [comment]
@Ingvix Aaaaaand 0.4 has made it into the store!

**Comment by Ingvix** [comment]
Nice, though I thought I said that removed the tablet UI support for I wasn't able to create a satisfying UI for it yet.

**Comment by hoelzro** [comment]
Whoops - I must have missed that comment.  I just removed tablet support - it should be removed from the store in a day or two.
